
export default [
  {
    title: 'Cooling',
    description: 'Cooling flavors, like with mint, feature a bright, fresh, sometimes inense sensation felt in your mouth and nose.',
    color: 'rgb(0, 185, 203)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Cooling.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Cooling_2_Dill_Mint_Ice_Cubes.jpg',
      '/assets/images/static-images/flavor-education/Cooling_6_Double_Chocolate_Chunk_Mint_Cookie.jpg',
      '/assets/images/static-images/flavor-education/Cooling_Chocolate-Mint-Crownie-Pie.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Beverages-Cocktails/Dill-Mint-Ice-Cubes',
      'http://www.mccormick.com/Recipes/Dessert/Double-Chocolate-Chunk-Mint-Cookies',
      'http://www.mccormick.com/Recipes/Dessert/Chocolate-Mint-Crownie-Pie',
    ],
    recipeBars: [
      20,
      60,
      90,
    ],
    recipeNames: [
      'Dill Mint Cubes',
      'Chocolate Chunk Mint Cookie',
      'Chocolate Mint Crownie Pie',
    ],
  },
  {
    title: 'Licorice',
    description: 'The sharp, fruity aroma and flavor associated with black licorice is also found in fennel, anise seed, basil, and is the distinct character of ouzo & sambuca.',
    color: 'rgb(0, 0, 0)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Licorice.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Licorice_1_Sweet_Basil_and_Oregano_Bruschetta_Chicken.jpg',
      '/assets/images/static-images/flavor-education/Licorice_5_Easy_Homemade_Root_Beer.jpg',
      '/assets/images/static-images/flavor-education/Licorice_8_Glazed_Anise_Cookies.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Gourmet/Recipes/Main-Dishes/Sweet-Basil-and-Oregano-Bruschetta-Chicken',
      'http://www.mccormick.com/Recipes/Beverages-Cocktails/Easy-Homemade-Root-Beer',
      'http://www.mccormick.com/Recipes/Dessert/Glazed-Anise-Cookies',
    ],
    recipeBars: [
      10,
      50,
      80,
    ],
    recipeNames: [
      'Sweet Basil and Oregano Bruschetta Chicken',
      'Easy Homemade Root Beer',
      'Glazed Anise Cookies',
    ],
  },
  {
    title: 'Woody',
    description: 'Woody refers to the light yet, distinct aroma and flavor associated with raw apples, cinnamon sticks, and freshly-cut cedar, oak and apple wood. Found in cedar plank grilled salmon or oak aged chardonnay.',
    color: 'rgb(115, 80, 45)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Woody.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Woody_2_Dukkah_Crusted_Fish_with_Broccoli_Red_Lentils.jpg',
      '/assets/images/static-images/flavor-education/Woody_LemonChicken.jpg',
      '/assets/images/static-images/flavor-education/Woody_5_Rosemary-Pork-Tenderloin-on-a-Bed-of-Spinach-Roasted-Red-Peppers-and-Prosciutto_Recipe.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Main-Dishes/Dukkah-Crusted-Fish-with-Broccoli-and-Red-Lentils',
      'http://www.mccormick.com/Recipes/Main-Dishes/Mediterranean-Lemon-Chicken',
      'http://www.mccormick.com/Gourmet/Recipes/Main-Dishes/Rosemary-Pork-Tenderloin-on-a-Bed-of-Spinach-Roasted-Red-Peppers-and-Prosciutto',
    ],
    recipeBars: [
      20,
      35,
      50,
    ],
    recipeNames: [
      'Dukkah Crusted Fish with Broccoli & Red Lentils',
      'Mediterranean Lemon Chicken',
      'Rosemary Pork Tenderloin on a Bed of Spinach Roasted Red Peppers & Prosciutto',
    ],
  },
  {
    title: 'Earthy',
    description: 'Earthy flavors are most reminiscent of foods such as mushrooms, potatoes and some red wines; thick, rich and full-bodied.',
    color: 'rgb(96, 38, 44)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Earthy.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Earthy_2_Buttery_Grilled_Mushrooms.jpg',
      '/assets/images/static-images/flavor-education/Earthy_5_Toasted_Onion_Garlic_Potatoes.jpg',
      '/assets/images/static-images/flavor-education/Earthy_9_Horseradish.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Grill-Mates/Recipes/Salads-Sides/Buttery-Grilled-Mushroom-Bundles',
      'http://www.mccormick.com/Recipes/Salads-Sides/Toasted-Onion-and-Garlic-Potatoes',
      null,
    ],
    recipeBars: [
      20,
      50,
      90,
    ],
    recipeNames: [
      'Buttery Grilled Mushroom Bundles',
      'Toasted Onion and Garlic Potatoes',
      'Horseradish',
    ],
  },
  {
    title: 'Vegetable',
    description: 'Vegetable is a distinct aroma and flavor that ranges in intensity among different vegetables such as: carrots, broccoli, corn and cabbage.',
    color: 'rgb(0, 155, 75)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Vegetable.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Vegetable_2_Eggplant-and-Goat-Cheese-Torte-with-Honey-Harissa-Sauce.jpg',
      '/assets/images/static-images/flavor-education/Vegetable_AsparagusMushroomQuesadillas.jpg',
      '/assets/images/static-images/flavor-education/Vegetable_9_Easy_Spinach_and_Artichoke_Dip_Adventures_in_Cooking.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Salads-Sides/Eggplant-and-Goat-Cheese-Torte-with-Honey-Harissa-Sauce',
      'http://www.mccormick.com/Gourmet/Recipes/Appetizer/Asparagus-and-Mushroom-Quesadillas',
      'http://www.mccormick.com/Recipes/Appetizer/Easy-Spinach-and-Artichoke-Dip',
    ],
    recipeBars: [
      36,
      50,
      80,
    ],
    recipeNames: [
      'Eggplant and Goat Cheese Torte with Honey Harissa Sauce',
      'Asparagus and Mushroom Quesadillas',
      'Easy Spinach and Artichoke Dip',
    ],
  },
  {
    title: 'Tomatoey',
    description: 'Tomatoey referes to the tangy, bright flavor of dishes that contain fresh, cooked or sun-dried tomato as a central ingredient.',
    color: 'rgb(227, 74, 39)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Tomatoey.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Tomatoey_2_Tomato_Soup_with_Grilled_Cheese_Croutons.jpg',
      '/assets/images/static-images/flavor-education/Tomatoey_5_Easy_Meat_Lasagna.jpg',
      '/assets/images/static-images/flavor-education/Tomatoey_9_Fried_Green_Tomatoes_with_Buttermilk_Chipotle_Dressing.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Gourmet/Recipes/Soups-Stews/Tomato-Soup-with-Grilled-Cheese-Croutons',
      'http://www.mccormick.com/Recipes/Main-Dishes/Easy-Meat-Lasagna',
      'http://www.mccormick.com/Gourmet/Recipes/Soups-Stews/Fried-Green-Tomato-Soup-with-Cornbread-Croutons',
    ],
    recipeBars: [
      20,
      50,
      90,
    ],
    recipeNames: [
      'Tomato Soup with Grilled Cheese Croutons',
      'Easy Meat Lasagna',
      'Fried Green Tomato Soup with Cornbread Croutons',
    ],
  },
  {
    title: 'Floral',
    description: 'Sweet and aromatic, floral notes range from light scents of rose to stronger perfumes of lavender. It is commonly associated with herbal teas, honey and essential oils.',
    color: 'rgb(188, 169, 210)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Floral.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Floral_2_Creamy_Carrot_Soup_with_Toasted_Cumin_and_Coriander.jpg',
      '/assets/images/static-images/flavor-education/Floral_4_Lemon_Ginger_Blueberry_Muffins.jpg',
      '/assets/images/static-images/flavor-education/Floral_LemonCurdTruffle.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Gourmet/Recipes/Soups-Stews/Creamy-Carrot-Soup-with-Toasted-Cumin-and-Coriander',
      'http://www.mccormick.com/Recipes/Breakfast-Brunch/Lemon-Ginger-Blueberry-Muffins',
      'http://www.mccormick.com/Recipes/Dessert/Lemon-Curd-Trifle',
    ],
    recipeBars: [
      20,
      40,
      75,
    ],
    recipeNames: [
      'Creamy Carrot Soup with Toasted Cumin and Coriander',
      'Lemon Ginger Blueberry Muffins',
      'Lemon Curd Trifle',
    ],
  },
  {
    title: 'Fruity',
    description: 'While not citrusy, fruity flavors combine the soft, bright and tart notes associated with ripe berries, apples and pears.',
    color: 'rgb(166, 56, 133)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Fruity.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Fruity_5_Carrot_Cake.jpg',
      '/assets/images/static-images/flavor-education/Fruity_6_Beef_Bourguignon.jpg',
      '/assets/images/static-images/flavor-education/Fruity_8_Easy_Lemon_Tea_Infused_Custard_with_Candied_Apricots.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Dessert/Carrot-Cake-with-Vanilla-Cream-Cheese-Frosting',
      'http://www.mccormick.com/Gourmet/Recipes/Main-Dishes/Beef-Bourguignon',
      'http://www.mccormick.com/Recipes/Dessert/Easy-Lemon-Tea-Infused-Custard-with-Candied-Apricots',
    ],
    recipeBars: [
      40,
      60,
      80,
    ],
    recipeNames: [
      'Carrot Cake',
      'Beef Bourguignon',
      'Easy Lemon Tea-Infused Custard with Candied Apricots',
    ],
  },
  {
    title: 'Citrusy',
    description: 'A little sweet and a little sour, citrusy flavor includes lemon, lime, grapefruit and orange.',
    color: 'rgb(209, 213, 47)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Citrusy.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Citrusy_3_Honey_Pineapple_Chicken.jpg',
      '/assets/images/static-images/flavor-education/Citrusy_7_Rack_of_Lamb_with_Quinoa_Hazelnut_Crust_and_Mint_Pesto_Gimme_Some_Oven.jpg',
      '/assets/images/static-images/flavor-education/Citrusy_9_Mixed_Berry_Pie.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Main-Dishes/Honey-Pineapple-Chicken-Stir-Fry',
      'http://www.mccormick.com/Gourmet/Recipes/Main-Dishes/Rack-of-Lamb-with-Quinoa-Hazelnut-Crust-and-Mint-Pesto',
      'http://www.mccormick.com/Recipes/Dessert/Mixed-Berry-Pie',
    ],
    recipeBars: [
      30,
      70,
      90,
    ],
    recipeNames: [
      'Honey Pineapple Chicken Stir-Fry',
      'Rack of Lamb with Quinoa-Hazelnut Crust and Mint Pesto',
      'Mixed Berry Pie',
    ],
  },
  {
    title: 'Sour',
    description: 'Whether you call it tart or biting, sour is one of the five basic tastes we experience when eating acidic foods such as citrus fruits and vinegars.',
    color: 'rgb(255, 231, 16)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Sour.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Sour_3_Thai_Ginger_Rubbed_Grilled_Salmon_with_Green_Curry_Sauce.jpg',
      '/assets/images/static-images/flavor-education/Sour_6_Hibiscus_Ancho_Sorbet_Gimme_Some_Oven.jpg',
      '/assets/images/static-images/flavor-education/Sour_9_Caribbean_Grilled_Tuna.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Gourmet/Recipes/Main-Dishes/Thai-Ginger-Rubbed-Grilled-Salmon-with-Green-Curry-Sauce',
      'http://www.mccormick.com/Gourmet/Recipes/Dessert/Hibiscus-Ancho-Sorbet',
      'http://www.mccormick.com/Recipes/Main-Dishes/Caribbean-Grilled-Tuna',
    ],
    recipeBars: [
      20,
      70,
      100,
    ],
    recipeNames: [
      'Thai Ginger Rubbed Grilled Salmon with Green Curry Sauce',
      'Hibiscus Ancho Sorbet',
      'Caribbean Grilled Tuna',
    ],
  },
  {
    title: 'Tropical',
    description: 'Bright and mostly sweet, Tropical flavors can have a sour bite as experienced with fresh pineapple. Tropical flavors range from fruits like coconut, guava and papaya to mango salsa and banana bread.',
    color: 'rgb(239, 86, 159)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Tropical.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Tropical_PineappleCoconutCooler.jpg',
      '/assets/images/static-images/flavor-education/Tropical_5_Rum_Ba_Fruit_Skewers.jpg',
      '/assets/images/static-images/flavor-education/Tropical_8_Double_Banana_Bread.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Beverages-Cocktails/Pineapple-Coconut-Cooler',
      'http://www.mccormick.com/Recipes/Dessert/Rum-Ba-Fruit-Skewers',
      'http://www.mccormick.com/Recipes/Breakfast-Brunch/Double-Banana-Bread',
    ],
    recipeBars: [
      20,
      50,
      80,
    ],
    recipeNames: [
      'Pineapple Coconut Cooler',
      'Rum Ba Fruit Skewers',
      'Double Banana Bread',
    ],
  },
  {
    title: 'Vanilla',
    description: 'Though associated with sweet flavors can be reminiscent of both marshmallow or bourbon, vanilla complements many desserts and sweet, baked dishes.',
    color: 'rgb(200, 191, 161)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Vanilla.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Vanilla_2_Quick_and_Easy_French_Toast.jpg',
      '/assets/images/static-images/flavor-education/Vanilla_6_Red_Tea_Smoked_Sea_Bass.jpg',
      '/assets/images/static-images/flavor-education/Vanilla_RaspberryWhiteCake.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Breakfast-Brunch/Easy-Cinnamon-French-Toast-with-Cinnamon-Syrup',
      'http://www.mccormick.com/Recipes/Main-Dishes/Red-Tea-Smoked-Sea-Bass-with-Cinnamon-Caramelized-Plums',
      'http://www.mccormick.com/Recipes/Dessert/Raspberry-White-Chocolate-Cake',
    ],
    recipeBars: [
      20,
      60,
      80,
    ],
    recipeNames: [
      'Easy Cinnamon French Toast with Cinnamon Syrup',
      'Red Tea Smoked Sea Bass with Cinnamon Caramelized Plums',
      'Raspberry White Chocolate Cake',
    ],
  },
  {
    title: 'Sweet',
    description: 'This sugary and mouth-watering basic taste is one of the more universally loved. It\'s commonly associated with honey soaked desserts, maple syrup drenched pancakes and frosting.',
    color: 'rgb(245, 156, 175)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Sweet.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Sweet_1_Citrus_Salmon_with_Orange_Relish.jpg',
      '/assets/images/static-images/flavor-education/Sweet_5_Raspberry_Brownies.jpg',
      '/assets/images/static-images/flavor-education/Sweet_9_Festive_Meringue_Cookies.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Main-Dishes/Citrus-Salmon-with-Orange-Relish',
      'http://www.mccormick.com/Recipes/Dessert/Raspberry-Brownies',
      'http://www.mccormick.com/Recipes/Dessert/Colorful-Meringue-Cookies',
    ],
    recipeBars: [
      10,
      50,
      90,
    ],
    recipeNames: [
      'Citrus Salmon with Orange Relish',
      'Raspberry Brownies',
      'Colorful Meringue Cookies',
    ],
  },
  {
    title: 'Warm Brown Spice',
    description: 'Reminiscent of the warm, welcoming scents associated with Fall, warm brown spice flavors include cinnamon, cloves, nutmeg and mace.',
    color: 'rgb(148, 58, 20)',
    mark: '/assets/images/static-images/flavor-education/FPMark_warm-brown-spice.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/WarmBrownSpice_2_Caramel_Pumpkin_Oatmeal_Bars.jpg',
      '/assets/images/static-images/flavor-education/WarmBrownSpice_5_Cinnamon_Jerk_Pork_Chops_with_Whipped_Barbados_Sweet_Potatoes.jpg',
      '/assets/images/static-images/flavor-education/WarmBrownSpice_PumpkinCakeRoll.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Dessert/Caramel-Pumpkin-Oatmeal-Bars',
      'http://www.mccormick.com/Gourmet/Recipes/Main-Dishes/Cinnamon-Jerk-Pork-Chops-with-Whipped-Sweet-Potatoes',
      'http://www.mccormick.com/Recipes/Dessert/Pumpkin-Cake-Roll-with-Cream-Cheese-Filling',
    ],
    recipeBars: [
      20,
      50,
      40,
    ],
    recipeNames: [
      'Caramel Pumpkin Oatmeal Bars',
      'Cinnamon Jerk Pork Chops with Whipped Sweet Potatoes',
      'Pumpkin Cake Roll with Cream Cheese Filling',
    ],
  },
  {
    title: 'Roasted/Toasted',
    description: 'Roasted and toasted refers to warm, slightly nutty and caramelized  flavors associated with buttered toast, crusts of artisan bread or the rich, outer layer of a standing rib roast.',
    color: 'rgb(150, 95, 36)',
    mark: '/assets/images/static-images/flavor-education/FPMark_roasted-toasted.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/RoastedToasted_1_Spiced_Pecan_Tarts.jpg',
      '/assets/images/static-images/flavor-education/RoastedToasted_4_Rye_on_Rye_Roast_Beef_Panini.jpg',
      '/assets/images/static-images/flavor-education/RoastedToasted_9_Peach_Blueberry_Crisp.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Gourmet/Recipes/Dessert/Spiced-Pecan-Tarts',
      'http://www.mccormick.com/Gourmet/Recipes/Main-Dishes/Rye-on-Rye-Roast-Beef-Panini',
      'http://www.mccormick.com/Recipes/Dessert/Peach-Blueberry-Crisp',
    ],
    recipeBars: [
      10,
      40,
      90,
    ],
    recipeNames: [
      'Spiced Pecan Tarts',
      'Rye on Rye Roast Beef Panini',
      'Peach Blueberry Crisp',
    ],
  },
  {
    title: 'Nutty',
    description: 'The unique flavor and aroma associated with all types of nuts, from creamy macadamia to fruity almonds. Nutty flavors are also associated with foods like sesame seeds, aged Gouda cheese, amaretto, and whole wheat bread.',
    color: 'rgb(182, 164, 102)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Nutty.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Nutty_3_Toasted_Sesame_Balsamic_Asparagus.jpg',
      '/assets/images/static-images/flavor-education/Nutty_6_Sesame_Ginger_Chicken_and_Asian_Slaw.jpg',
      '/assets/images/static-images/flavor-education/Nutty_8_Plum_and_Brie_Dessert_Panini.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Gourmet/Recipes/Salads-Sides/Toasted-Sesame-Balsamic-Asparagus',
      'http://www.mccormick.com/Lawrys/Recipes/Main-Dishes/Sesame-Ginger-Chicken-and-Asian-Slaw',
      'http://www.mccormick.com/Gourmet/Recipes/Dessert/Plum-and-Brie-Dessert-Panini',
    ],
    recipeBars: [
      30,
      60,
      80,
    ],
    recipeNames: [
      'Toasted Sesame Balsamic Asparagus',
      'Sesame Ginger Chicken and Asian Slaw',
      'Plum and Brie Dessert Panini',
    ],
  },
  {
    title: 'Yeasty',
    description: 'Yeasty flavor is best described by the aroma that fills the air when fresh bread is baked or the aroma of a full-bodied beer.',
    color: 'rgb(146, 140, 116)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Yeasty.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Yeasty_3_Herb_Mushroom_and_Wild_Rice_Stuffing.jpg',
      '/assets/images/static-images/flavor-education/Yeasty_5_Lemon_Ricotta_Pancakes.jpg',
      '/assets/images/static-images/flavor-education/Yeasty_9_Beer_Can_Chicken.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Gourmet/Recipes/Salads-Sides/Herb-Mushroom-and-Wild-Rice-Stuffing',
      'http://www.mccormick.com/Recipes/Breakfast-Brunch/Lemon-Ricotta-Pancakes-with-Lemon-Ricotta-Cream',
      'http://www.mccormick.com/Grill-Mates/Recipes/Main-Dishes/Beer-Can-Chicken',
    ],
    recipeBars: [
      30,
      50,
      90,
    ],
    recipeNames: [
      'Herb Mushroom and Wild Rice Stuffing',
      'Lemon Ricotta Pancakes with Lemon Ricotta Cream',
      'Beer Can Chicken',
    ],
  },
  {
    title: 'Starchy',
    description: 'Starchy flavors are subtle in corn and white rice but stronger in boiled beans, potatoes and pasta. Though perceived as bland and sometimes difficult to detect, they make great carriers for sauces.',
    color: 'rgb(199, 200, 202)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Starchy.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Starchy_1_Tuscan_Pasta.jpg',
      '/assets/images/static-images/flavor-education/Starchy_4_Easier_Than_Pear_Pie.jpg',
      '/assets/images/static-images/flavor-education/Starchy_CinnamonOatmealCustardBars.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Main-Dishes/Tuscan-Pasta',
      'http://www.mccormick.com/Recipes/Dessert/Easier-Than-Pear-Pie',
      'http://www.mccormick.com/Recipes/Dessert/Cinnamon-Oatmeal-Custard-Bars-with-Rum-Raisin-Sauce',
    ],
    recipeBars: [
      10,
      40,
      70,
    ],
    recipeNames: [
      'Tuscan Pasta',
      'Easier Than Pear Pie',
      'Cinnamon Oatmeal Custard Bars with Rum Raisin Sauce',
    ],
  },
  {
    title: 'Caramelized',
    description: '\n                                    As sugar caramelizes, it takes on a smooth, buttery sweet flavor, much like you\'ll find in toffee or caramel sauce.\n                                ',
    color: 'rgb(208, 128, 55)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Caramelized.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Caramelized_1_Maple_Glaze_Donuts.jpg',
      '/assets/images/static-images/flavor-education/Caramelized_5_Caramel_Almond_Popcorn.jpg',
      '/assets/images/static-images/flavor-education/Caramelized_PoachedPear.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Breakfast-Brunch/Mini-Baked-Donuts-with-Maple-Glaze',
      'http://www.mccormick.com/Recipes/Appetizer/Caramel-Almond-Popcorn',
      'http://www.mccormick.com/Recipes/Dessert/Thyme-and-Cinnamon-Poached-Pears',
    ],
    recipeBars: [
      10,
      50,
      85,
    ],
    recipeNames: [
      'Mini Baked Donuts with Maple Glaze',
      'Caramel Almond Popcorn',
      'Thyme and Cinnamon Poached Pears',
    ],
  },
  {
    title: 'Buttery',
    description: '\n                                    Buttery flavor is a mild, soft and slightly sweet, fatty flavor common foods other than butter like olive oil and pistachios.\n                                ',
    color: 'rgb(254, 243, 160)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Buttery.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Buttery_3_Fiery_Kickoff_wings.jpg',
      '/assets/images/static-images/flavor-education/Buttery_6_Crostini_with_Hummus_and_Roasted_Red_Peppers.jpg',
      '/assets/images/static-images/flavor-education/Buttery_8_Tiramisu_Trifle_Parafaits.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Grill-Mates/Recipes/Appetizer/Fiery-Kickoff-Wings',
      'http://www.mccormick.com/Gourmet/Recipes/Appetizer/Crostini-with-Hummus-and-Roasted-Red-Peppers',
      'http://www.mccormick.com/Recipes/Dessert/Tiramisu-Trifle-Parfaits',
    ],
    recipeBars: [
      30,
      60,
      80,
    ],
    recipeNames: [
      'Fiery Kickoff Wings',
      'Crostini with Hummus and Roasted Red Peppers',
      'Tiramisu Trifle Parfaits',
    ],
  },
  {
    title: 'Sweet Cream',
    description: 'Sweet cream refers to the sweet and fatty flavor associated with whipping cream, cream cheese and ice cream.',
    color: 'rgb(232, 222, 196)',
    mark: '/assets/images/static-images/flavor-education/FPMark_sweet-cream.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/SweetCream_2_Easy_Creamy_Garlic_Fettuccine_Alfredo.jpg',
      '/assets/images/static-images/flavor-education/SweetCream_5_Cheesecake_Tart_with_Popcorn_Crust_and_Berries.jpg',
      '/assets/images/static-images/flavor-education/SweetCream_CarrotCakeMascarponeFrosting.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Main-Dishes/Easy-Creamy-Garlic-Fettuccine-Alfredo',
      'http://www.mccormick.com/Gourmet/Recipes/Dessert/Cheesecake-Tart-with-Popcorn-Crust-and-Berries',
      'http://www.mccormick.com/Gourmet/Recipes/Dessert/Carrot-Cake-with-Mascarpone-Cream-Cheese-Frosting',
    ],
    recipeBars: [
      20,
      50,
      90,
    ],
    recipeNames: [
      'Easy Creamy Garlic Fettuccine Alfredo',
      'Cheesecake Tart with Popcorn Crust and Berries',
      'Carrot Cake with Mascarpone Cream Cheese Frosting',
    ],
  },
  {
    title: 'Cheesy',
    description: 'Cheesy ranges in degrees of boldness, sharpness and fruitiness that you find in cheddar, Swiss and parmesan. Cheesy flavors are adored in classics like macaroni & cheese, fondue, and manicotti.',
    color: 'rgb(252, 175, 23)',
    mark: '/assets/images/static-images/flavor-education/FPMark_cheesy.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Cheesy_5_Three_Cheese_Lasagna.jpg',
      '/assets/images/static-images/flavor-education/Cheesy_7_Broccoli_Cauliflower_Casserole.jpg',
      '/assets/images/static-images/flavor-education/Cheesy_9_Arugula_and_Pine_Nut_Pesto.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Main-Dishes/Lasagna-Formaggio',
      'http://www.mccormick.com/Recipes/Salads-Sides/Broccoli-Cauliflower-Casserole',
      'http://www.mccormick.com/Recipes/Sauces/Arugula-Pesto',
    ],
    recipeBars: [
      45,
      70,
      90,
    ],
    recipeNames: [
      'Lasagna Formaggio',
      'Broccoli Cauliflower Casserole',
      'Arugula Pesto',
    ],
  },
  {
    title: 'Umami',
    description: '\n                                    Umami is a savory, mouthwatering basic taste associated with mushrooms, tomatoes, and soy sauce.\n                                ',
    color: 'rgb(74, 50, 115)',
    mark: '/assets/images/static-images/flavor-education/FPMark_umami.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Umami_3_Spinach_and_Mushroom_Risotto_Two_Peas_and_Their_Pod.jpg',
      '/assets/images/static-images/flavor-education/Umami_7_Ginger_Honey_Glazed_Salmon.jpg',
      '/assets/images/static-images/flavor-education/Umami_9_Easy_Fried_Rice.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Gourmet/Recipes/Main-Dishes/Spinach-and-Mushroom-Risotto',
      'http://www.mccormick.com/Recipes/Main-Dishes/Ginger-Honey-Glazed-Salmon',
      'http://www.mccormick.com/Recipes/Salads-Sides/Easy-Fried-Rice',
    ],
    recipeBars: [
      30,
      70,
      90,
    ],
    recipeNames: [
      'Spinach and Mushroom Risotto',
      'Ginger Honey Glazed Salmon',
      'Easy Fried Rice',
    ],
  },
  {
    title: 'Smoky',
    description: 'With a deep, chargrilled aroma, smoky flavors can bring to mind touches of several flavors— pecan or apple wood in bacon, or stronger notes of oak, mesquite, and hickory in whiskeys and BBQ ribs.',
    color: 'rgb(185, 187, 188)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Smoky.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Smoky_3_Grilled_Oysters_with_Grapefruit_Red_Pepper_Relish.jpg',
      '/assets/images/static-images/flavor-education/Smoky_5_Louisiana_Creole_Gumbo.jpg',
      '/assets/images/static-images/flavor-education/Smoky_9_Bag_n_Season_Smoky_Western_Spareribs.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Main-Dishes/Dukkah-Crusted-Fish-with-Broccoli-and-Red-Lentils',
      'http://www.mccormick.com/Zatarains/Recipes/Soups-Stews/Creole-Gumbo',
      'http://www.mccormick.com/Recipes/Main-Dishes/Bag-n-Season-Smoky-Western-Spareribsn',
    ],
    recipeBars: [
      30,
      50,
      90,
    ],
    recipeNames: [
      'Grilled Oysters with Grapefruit and Red Pepper Relish',
      'Creole Gumbo',
      'Bag’n Season Smoky Western Spareribs',
    ],
  },
  {
    title: 'Bitter',
    description: 'We vary in our sensitivity to bitterness, a basic taste. Some enjoy the distinct taste making dark chocolate, coffee and radicchio favorites while others find the taste harsh and unpleasant.',
    color: 'rgb(244, 122, 92)',
    mark: '/assets/images/static-images/flavor-education/FPMark_bitter.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Bitter_1_Double_Cinnamon_Sugar_Cookies.jpg',
      '/assets/images/static-images/flavor-education/Bitter_5_Classic_Hummus.jpg',
      '/assets/images/static-images/flavor-education/Bitter_9_Radicchio.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Dessert/Double-Cinnamon-Sugar-Cookies',
      'http://www.mccormick.com/Recipes/Appetizer/Classic-Hummus',
      null,
    ],
    recipeBars: [
      10,
      50,
      90,
    ],
    recipeNames: [
      'Double Cinnamon Sugar Cookies',
      'Classic Hummus',
      'Radicchio',
    ],
  },
  {
    title: 'Pungent Spice',
    description: 'Pungent spice refers to the sharp almost stinging sensation felt throughout your nose and mouth when enjoying wasabi, coarse grain mustard or horseradish. They may even make your eyes water just a bit.',
    color: 'rgb(178, 165, 21)',
    mark: '/assets/images/static-images/flavor-education/FPMark_Pungent-spice.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/PungentSpice_3_Gingered_Cranberry_Chutney_Eats_Well_with_Others.jpg',
      '/assets/images/static-images/flavor-education/PungentSpice_ChipotleChickenTacos.jpg',
      '/assets/images/static-images/flavor-education/PungentSpice_8_Grilled_Asparagus_with_Orange_Wasabi_Dressing.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Gourmet/Recipes/Sauces/Ginger-Cranberry-Chutney',
      'http://www.mccormick.com/Recipes/Main-Dishes/Chipotle-Chicken-Tacos',
      'http://www.mccormick.com/Gourmet/Recipes/Salads-Sides/Grilled-Asparagus-with-Orange-Wasabi-Dressing',
    ],
    recipeBars: [
      30,
      65,
      80,
    ],
    recipeNames: [
      'Ginger Cranberry Chutney',
      'Chipotle Chicken Tacos',
      'Grilled Asparagus with Orange Wasabi Dressing',
    ],
  },
  {
    title: 'Peppery',
    description: '\n                                    Whether using black, white or green peppercorns, peppery flavors take on a woody aroma and flavor and add a warm bite to foods.\n                                ',
    color: 'rgb(91, 84, 81)',
    mark: '/assets/images/static-images/flavor-education/FPMark_peppery.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Peppery_1_Lemon_Pepper_Spinach_Salad_Gimme_Some_Oven.jpg',
      '/assets/images/static-images/flavor-education/Peppery_5_Chai_Sugar_Cookies.jpg',
      '/assets/images/static-images/flavor-education/Peppery_9_Slow_Cooker_Pulled_Beef.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Main-Dishes/Lemon-Pepper-Spinach-Salad-with-Chicken',
      'http://www.mccormick.com/Gourmet/Recipes/Dessert/Chai-Sugar-Cookies',
      'http://www.mccormick.com/Recipes/Main-Dishes/Slow-Cookers-BBQ-Pulled-Chicken',
    ],
    recipeBars: [
      10,
      50,
      90,
    ],
    recipeNames: [
      'Lemon Pepper Spinach Salad with Chicken',
      'Chai Sugar Cookies',
      'Slow Cookers BBQ Pulled Chicken',
    ],
  },
  {
    title: 'Heat',
    description: 'Heat refers to the burning sensation felt in the mouth and throat, experienced slightly when you eat black pepper or ginger and more intensely with chile peppers like jalapenos or habaneros.',
    color: 'rgb(207, 34, 41)',
    mark: '/assets/images/static-images/flavor-education/FPMark_heat.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Heat_3_Orange_and_Radish_Salad_with_Cinnamon_Vinaigrette.jpg',
      '/assets/images/static-images/flavor-education/Heat_7_Peri_Peri_Chicken_Wings_with_Dipping_Sauces_Two_Peas_and_Their_Pod.jpg',
      '/assets/images/static-images/flavor-education/Heat_9_Ghost_Chilies.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Gourmet/Recipes/Salads-Sides/Orange-and-Radish-Salad-with-Cinnamon-Vinaigrette',
      'http://www.mccormick.com/Gourmet/Recipes/Appetizer/Peri-Peri-Chicken-Wings-with-Dipping-Sauce',
      null,
    ],
    recipeBars: [
      30,
      70,
      100,
    ],
    recipeNames: [
      'Orange and Radish Salad with Cinnamon Vinaigrette',
      'Peri Peri Chicken Wings with Dipping Sauce',
      'Ghost Chilies',
    ],
  },
  {
    title: 'Salty',
    description: '\n                                    Salty is one of the five basic tastes. Capers, anchovies, pickles and cured meat to name a few will conjure this sharp taste.\n                                ',
    color: 'rgb(111, 175, 167)',
    mark: '/assets/images/static-images/flavor-education/FPMark_salty.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/Salty_1_Ham_and_Cheese_Breakfast_Burritos.jpg',
      '/assets/images/static-images/flavor-education/Salty_4_Arugula_Salad_with_Blue_Cheese_and_Pecans_Eats_Well.jpg',
      '/assets/images/static-images/flavor-education/Salty_9_Baja_Chipotle_Chicken_Wings_Drummet.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Breakfast-Brunch/Ham-and-Cheese-Breakfast-Burritos',
      'http://www.mccormick.com/Gourmet/Recipes/Salads-Sides/Arugula-Salad-with-Blue-Cheese-and-Pecans',
      'http://www.mccormick.com/Lawrys/Recipes/Appetizer/Baja-Chipotle-Chicken-Drumettes',
    ],
    recipeBars: [
      10,
      40,
      90,
    ],
    recipeNames: [
      'Ham and Cheese Breakfast Burritos',
      'Arugula Salad with Blue Cheese and Pecans',
      'Mediterranean Lemon Chicken',
    ],
  },
  {
    title: 'Herby (Fresh)',
    description: '\n                                    Herby fresh refers to the strong, fresh, green aroma and flavor associated with herbs like basil in pesto and parsley in tabbouleah salad.\n                                ',
    color: 'rgb(174, 212, 119)',
    mark: '/assets/images/static-images/flavor-education/FPMark_herby-fresh.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/HerbyFresh_2_Coconut_Almond_Chicken_Stew_with_Cilantro.jpg',
      '/assets/images/static-images/flavor-education/HerbyFresh_4_Spice_Rubbed_Grilled_Steak_With_Chimichurri_Potato_Salad.jpg',
      '/assets/images/static-images/flavor-education/HerbyFresh_9_Steamed_Mussels_Artichokes_Hazel.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Gourmet/Recipes/Main-Dishes/Coconut-Almond-Chicken-Stew-with-Cilantro',
      'http://www.mccormick.com/Gourmet/Recipes/Main-Dishes/Spice-Rubbed-Grilled-Steak-with-Chimichurri-Potato-Salad',
      'http://www.mccormick.com/Recipes/Main-Dishes/Steamed-Mussels-and-Artichokes-with-Hazelnut-Gremolata',
    ],
    recipeBars: [
      20,
      40,
      90,
    ],
    recipeNames: [
      'Coconut Almond Chicken Stew with Cilantro',
      'Spice-Rubbed Grilled Steak with Chimichurri Potato Salad',
      'Steamed Mussels and Artichokes with Hazelnut Gremolata',
    ],
  },
  {
    title: 'Herby (Woody)',
    description: 'Herby Woody refers to a combination of freshly cut wood and green herbs. The aroma and flavors are found in green tea and dry herbs like oregano, rosemary and thyme.',
    color: 'rgb(61, 113, 58)',
    mark: '/assets/images/static-images/flavor-education/FPMark_herby-woody.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/HerbyWoody_1_Greek_Roasted_Chicken.jpg',
      '/assets/images/static-images/flavor-education/HerbyWoody_3_Apple_Sage_Tart_Tatin.jpg',
      '/assets/images/static-images/flavor-education/HerbyWoody_8_Baked-Ziti.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Gourmet/Recipes/Main-Dishes/Greek-Roasted-Chicken',
      'http://www.mccormick.com/Recipes/Dessert/Apple-Sage-Tarte-Tatin',
      'http://www.mccormick.com/Recipes/Main-Dishes/Baked-Ziti',
    ],
    recipeBars: [
      10,
      30,
      80,
    ],
    recipeNames: [
      'Greek Roasted Chicken',
      'Apple Sage Tarte Tatin',
      'Baked Ziti',
    ],
  },
  {
    title: 'Coffee/Chocolatey',
    description: 'Coffee/Chocolatey refers less to milk chocolate candy and more to the darker, slightly bitter, roasted coffee or cocoa beans.',
    color: 'rgb(75, 38, 17)',
    mark: '/assets/images/static-images/flavor-education/FPMark_coffee-chocolately.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/CoffeeChocolatey_Easy_Homemade_Root_Beer.jpg',
      '/assets/images/static-images/flavor-education/CoffeeChocolate_5_Tiramisu_Baked_by_Rachel.jpg',
      '/assets/images/static-images/flavor-education/CoffeeChocolate_8_Mexican_Coffee.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Beverages-Cocktails/Easy-Homemade-Root-Beer',
      'http://www.mccormick.com/Recipes/Dessert/Tiramisu',
      'http://www.mccormick.com/Recipes/Beverages-Cocktails/Mexican-Coffeen',
    ],
    recipeBars: [
      20,
      50,
      80,
    ],
    recipeNames: [
      'Easy Homemade Root Beer',
      'Tiramisu',
      'Mexican Coffee',
    ],
  },
  {
    title: 'Garlic/Onionish',
    description: '\n                                    Fresh garlic and onion flavors can carry a sharp punch, but when cooked, they become sweet, mild and creamy.\n                                ',
    color: 'rgb(220, 210, 135)',
    mark: '/assets/images/static-images/flavor-education/FPMark_garlic-onionish.jpg',
    recipeImages: [
      '/assets/images/static-images/flavor-education/GarlicOnionish_2_Dukkah_Crusted_Fish_with_Broccoli_Red_Lentils.jpg',
      '/assets/images/static-images/flavor-education/GarlicOnionish_4_Classic_Greek_Salad.jpg',
      '/assets/images/static-images/flavor-education/GarlicOnionish_9_Arugula_and_Pine_Nut_Pesto.jpg',
    ],
    recipeLinks: [
      'http://www.mccormick.com/Recipes/Main-Dishes/Dukkah-Crusted-Fish-with-Broccoli-and-Red-Lentils',
      'http://www.mccormick.com/Gourmet/Recipes/Salads-Sides/Classic-Greek-Salad',
      'http://www.mccormick.com/Recipes/Sauces/Arugula-Pesto',
    ],
    recipeBars: [
      20,
      40,
      90,
    ],
    recipeNames: [
      'Dukkah Crusted Fish with Broccoli & Red Lentils',
      'Classic Greek Salad',
      'Arugula Pesto',
    ],
  },
];
