
export const APP_LAUNCHED = 'APP_LAUNCHED';
export const BANNER_CLICKED = 'BANNER_CLICKED';
export const COOKBOOK_VIEW = 'COOKBOOK_VIEW';
export const ONBOARDING_STEP_ACTION = 'ONBOARDING_STEP_ACTION';
export const ONBOARDING_VISIBLE = 'ONBOARDING_VISIBLE';
export const RECIPE_FEED_VIEW = 'RECIPE_FEED_VIEW';
export const RECIPE_ORIGIN = 'RECIPE_ORIGIN';
export const RECIPE_PRINT = 'RECIPE_PRINT';
export const RECIPE_VIEW = 'RECIPE_VIEW';
export const SHOPPING_LIST_PRINT = 'SHOPPING_LIST_PRINT';
export const URL_SHARING = 'URL_SHARING';

export default {
  APP_LAUNCHED,
  BANNER_CLICKED,
  COOKBOOK_VIEW,
  ONBOARDING_STEP_ACTION,
  ONBOARDING_VISIBLE,
  RECIPE_FEED_VIEW,
  RECIPE_ORIGIN,
  RECIPE_PRINT,
  RECIPE_VIEW,
  SHOPPING_LIST_PRINT,
  URL_SHARING,
};
