
export const AUTH_DATA = 'AUTH_DATA';
export const JWT_HEADER = 'JWT_HEADER';
export const MIXPANEL_FIRST_VISIT_DATE = 'MIXPANEL_FIRST_VISIT_DATE';
export const PEAPOD_CONFIG = 'PEAPOD_CONFIG';
export const SHOPPING_LIST_VIEW = 'SHOPPING_LIST_VIEW';

export default {
  AUTH_DATA,
  JWT_HEADER,
  MIXPANEL_FIRST_VISIT_DATE,
  PEAPOD_CONFIG,
  SHOPPING_LIST_VIEW,
};
