
export const NOT_NEW_USER = 'NOT_NEW_USER';
export const ONBOARDING_LAST_SEEN = 'ONBOARDING_LAST_SEEN';
export const POPULAR_SHOPPING_LIST_ITEMS = 'POPULAR_SHOPPING_LIST_ITEMS';
export const SHOPPING_LIST_OPERATIONS = 'SHOPPING_LIST_OPERATIONS';

export default {
  NOT_NEW_USER,
  ONBOARDING_LAST_SEEN,
  POPULAR_SHOPPING_LIST_ITEMS,
  SHOPPING_LIST_OPERATIONS,
};
