
export const AUTHENTICATION = 'AUTHENTICATION';
export const COOKBOOK_COLLECTIONS = 'COOKBOOK_COLLECTIONS';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const ONBOARDING = 'ONBOARDING';
export const REQUEST_RESET_PASSWORD = 'REQUEST_RESET_PASSWORD';
export const SEARCH = 'SEARCH';
export const USE_SHOPPING_LIST_IN_STORE = 'USE_SHOPPING_LIST_IN_STORE';
export const SEARCH_FILTERS = 'SEARCH_FILTERS';
export const SEND_ITEMS_TO_INVENTORY = 'SEND_ITEMS_TO_INVENTORY';
export const SEND_ITEMS_TO_PEAPOD = 'SEND_ITEMS_TO_PEAPOD';
export const CHECKOUT_PROCESS = 'CHECKOUT_PROCESS';
export const FIND_ALTERNATIVES = 'FIND_ALTERNATIVES';

export default {
  AUTHENTICATION,
  COOKBOOK_COLLECTIONS,
  DELETE_ACCOUNT,
  DELETE_RECIPE,
  ONBOARDING,
  REQUEST_RESET_PASSWORD,
  SEARCH,
  USE_SHOPPING_LIST_IN_STORE,
  SEARCH_FILTERS,
  SEND_ITEMS_TO_INVENTORY,
  SEND_ITEMS_TO_PEAPOD,
  CHECKOUT_PROCESS,
  FIND_ALTERNATIVES,
};
