
export const AUTHENTICATION = 'AUTHENTICATION';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const ONBOARDING = 'ONBOARDING';
export const REQUEST_RESET_PASSWORD = 'REQUEST_RESET_PASSWORD';

export default {
  AUTHENTICATION,
  DELETE_ACCOUNT,
  ONBOARDING,
  REQUEST_RESET_PASSWORD,
};
