
export const ABOUT_YOURSELF = 'ABOUT_YOURSELF';
export const SPECIAL_DIETS = 'SPECIAL_DIETS';
export const ALLERGIES = 'ALLERGIES';
export const AVOIDANCES = 'AVOIDANCES';
export const INVENTORIES = 'INVENTORIES';
export const COMBINED_AVOIDANCES = 'COMBINED_AVOIDANCES';

export const AUTHENTICATION = 'AUTHENTICATION';
export const WELCOME = 'WELCOME';

export const STEPS = [
  COMBINED_AVOIDANCES,
];

export const OUTDATED_STEPS = [
  SPECIAL_DIETS, ALLERGIES, ABOUT_YOURSELF, AVOIDANCES, INVENTORIES,
];
