apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flavorprint
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flavorprint
        env: production
    spec:
      containers:
      - name: flavorprint
        image: eu.gcr.io/robotic-energy-88923/flavorprint:0.0.1
        env:
          - name: "APP_ENV"
            value: "production"
          - name: "APP_DOMAIN"
            value: "fp.whisk.com"
          - name: "PORT"
            value: "3000"
        ports:
        - containerPort: 3000
        livenessProbe:
          # an http probe
          httpGet:
            path: /health-check
            port: 3000
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: flavorprint-service
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: flavorprint
    env: production
